//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NorthwindModel", "Products_FK01", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InventoryWebChart.Category), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InventoryWebChart.Product), true)]

#endregion

namespace InventoryWebChart
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NorthwindEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
        /// </summary>
        public NorthwindEntities() : base("name=NorthwindEntities", "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        public NorthwindEntities(string connectionString) : base(connectionString, "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        public NorthwindEntities(EntityConnection connection) : base(connection, "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="category_ID">Initial value of the Category_ID property.</param>
        /// <param name="category_Name">Initial value of the Category_Name property.</param>
        public static Category CreateCategory(global::System.Int32 category_ID, global::System.String category_Name)
        {
            Category category = new Category();
            category.Category_ID = category_ID;
            category.Category_Name = category_Name;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Category_ID
        {
            get
            {
                return _Category_ID;
            }
            set
            {
                if (_Category_ID != value)
                {
                    OnCategory_IDChanging(value);
                    ReportPropertyChanging("Category_ID");
                    _Category_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Category_ID");
                    OnCategory_IDChanged();
                }
            }
        }
        private global::System.Int32 _Category_ID;
        partial void OnCategory_IDChanging(global::System.Int32 value);
        partial void OnCategory_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category_Name
        {
            get
            {
                return _Category_Name;
            }
            set
            {
                OnCategory_NameChanging(value);
                ReportPropertyChanging("Category_Name");
                _Category_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category_Name");
                OnCategory_NameChanged();
            }
        }
        private global::System.String _Category_Name;
        partial void OnCategory_NameChanging(global::System.String value);
        partial void OnCategory_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Picture
        {
            get
            {
                return StructuralObject.GetValidValue(_Picture);
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.Byte[] _Picture;
        partial void OnPictureChanging(global::System.Byte[] value);
        partial void OnPictureChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK01", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("NorthwindModel.Products_FK01", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("NorthwindModel.Products_FK01", "Products", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        /// <param name="product_Name">Initial value of the Product_Name property.</param>
        /// <param name="discontinued">Initial value of the Discontinued property.</param>
        public static Product CreateProduct(global::System.Int32 product_ID, global::System.String product_Name, global::System.Boolean discontinued)
        {
            Product product = new Product();
            product.Product_ID = product_ID;
            product.Product_Name = product_Name;
            product.Discontinued = discontinued;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                if (_Product_ID != value)
                {
                    OnProduct_IDChanging(value);
                    ReportPropertyChanging("Product_ID");
                    _Product_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_ID");
                    OnProduct_IDChanged();
                }
            }
        }
        private global::System.Int32 _Product_ID;
        partial void OnProduct_IDChanging(global::System.Int32 value);
        partial void OnProduct_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Supplier_ID
        {
            get
            {
                return _Supplier_ID;
            }
            set
            {
                OnSupplier_IDChanging(value);
                ReportPropertyChanging("Supplier_ID");
                _Supplier_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Supplier_ID");
                OnSupplier_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Supplier_ID;
        partial void OnSupplier_IDChanging(Nullable<global::System.Int32> value);
        partial void OnSupplier_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Category_ID
        {
            get
            {
                return _Category_ID;
            }
            set
            {
                OnCategory_IDChanging(value);
                ReportPropertyChanging("Category_ID");
                _Category_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category_ID");
                OnCategory_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Category_ID;
        partial void OnCategory_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCategory_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product_Name
        {
            get
            {
                return _Product_Name;
            }
            set
            {
                OnProduct_NameChanging(value);
                ReportPropertyChanging("Product_Name");
                _Product_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_Name");
                OnProduct_NameChanged();
            }
        }
        private global::System.String _Product_Name;
        partial void OnProduct_NameChanging(global::System.String value);
        partial void OnProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String English_Name
        {
            get
            {
                return _English_Name;
            }
            set
            {
                OnEnglish_NameChanging(value);
                ReportPropertyChanging("English_Name");
                _English_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("English_Name");
                OnEnglish_NameChanged();
            }
        }
        private global::System.String _English_Name;
        partial void OnEnglish_NameChanging(global::System.String value);
        partial void OnEnglish_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Quantity_Per_Unit
        {
            get
            {
                return _Quantity_Per_Unit;
            }
            set
            {
                OnQuantity_Per_UnitChanging(value);
                ReportPropertyChanging("Quantity_Per_Unit");
                _Quantity_Per_Unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Quantity_Per_Unit");
                OnQuantity_Per_UnitChanged();
            }
        }
        private global::System.String _Quantity_Per_Unit;
        partial void OnQuantity_Per_UnitChanging(global::System.String value);
        partial void OnQuantity_Per_UnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Unit_Price
        {
            get
            {
                return _Unit_Price;
            }
            set
            {
                OnUnit_PriceChanging(value);
                ReportPropertyChanging("Unit_Price");
                _Unit_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Unit_Price");
                OnUnit_PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Unit_Price;
        partial void OnUnit_PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnUnit_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Units_In_Stock
        {
            get
            {
                return _Units_In_Stock;
            }
            set
            {
                OnUnits_In_StockChanging(value);
                ReportPropertyChanging("Units_In_Stock");
                _Units_In_Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Units_In_Stock");
                OnUnits_In_StockChanged();
            }
        }
        private Nullable<global::System.Int16> _Units_In_Stock;
        partial void OnUnits_In_StockChanging(Nullable<global::System.Int16> value);
        partial void OnUnits_In_StockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Units_On_Order
        {
            get
            {
                return _Units_On_Order;
            }
            set
            {
                OnUnits_On_OrderChanging(value);
                ReportPropertyChanging("Units_On_Order");
                _Units_On_Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Units_On_Order");
                OnUnits_On_OrderChanged();
            }
        }
        private Nullable<global::System.Int16> _Units_On_Order;
        partial void OnUnits_On_OrderChanging(Nullable<global::System.Int16> value);
        partial void OnUnits_On_OrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Reorder_Level
        {
            get
            {
                return _Reorder_Level;
            }
            set
            {
                OnReorder_LevelChanging(value);
                ReportPropertyChanging("Reorder_Level");
                _Reorder_Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reorder_Level");
                OnReorder_LevelChanged();
            }
        }
        private Nullable<global::System.Int16> _Reorder_Level;
        partial void OnReorder_LevelChanging(Nullable<global::System.Int16> value);
        partial void OnReorder_LevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Discontinued
        {
            get
            {
                return _Discontinued;
            }
            set
            {
                OnDiscontinuedChanging(value);
                ReportPropertyChanging("Discontinued");
                _Discontinued = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discontinued");
                OnDiscontinuedChanged();
            }
        }
        private global::System.Boolean _Discontinued;
        partial void OnDiscontinuedChanging(global::System.Boolean value);
        partial void OnDiscontinuedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK01", "Categories")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
