'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute()>
#Region "EDM Relationship Metadata"

<Assembly: EdmRelationshipAttribute("NorthwindModel", "Products_FK01", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(InventoryWebChart.Category), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(InventoryWebChart.Product), True)>

#End Region

Namespace InventoryWebChart
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class NorthwindEntities
		Inherits ObjectContext
		#Region "Constructors"

		''' <summary>
		''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=NorthwindEntities", "NorthwindEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "NorthwindEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connection As EntityConnection)
			MyBase.New(connection, "NorthwindEntities")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Categories() As ObjectSet(Of Category)
			Get
				If (_Categories Is Nothing) Then
					_Categories = MyBase.CreateObjectSet(Of Category)("Categories")
				End If
				Return _Categories
			End Get
		End Property
		Private _Categories As ObjectSet(Of Category)

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Products() As ObjectSet(Of Product)
			Get
				If (_Products Is Nothing) Then
					_Products = MyBase.CreateObjectSet(Of Product)("Products")
				End If
				Return _Products
			End Get
		End Property
		Private _Products As ObjectSet(Of Product)

		#End Region

		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToCategories(ByVal category As Category)
			MyBase.AddObject("Categories", category)
		End Sub

		''' <summary>
		''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToProducts(ByVal product As Product)
			MyBase.AddObject("Products", product)
		End Sub

		#End Region

	End Class

	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Category"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class Category
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new Category object.
		''' </summary>
		''' <param name="category_ID">Initial value of the Category_ID property.</param>
		''' <param name="category_Name">Initial value of the Category_Name property.</param>
		Public Shared Function CreateCategory(ByVal category_ID As Global.System.Int32, ByVal category_Name As Global.System.String) As Category
			Dim category As New Category()
			category.Category_ID = category_ID
			category.Category_Name = category_Name
			Return category
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property Category_ID() As Global.System.Int32
			Get
				Return _Category_ID
			End Get
			Set(ByVal value As System.Int32)
				If _Category_ID <> value Then
					OnCategory_IDChanging(value)
					ReportPropertyChanging("Category_ID")
					_Category_ID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("Category_ID")
					OnCategory_IDChanged()
				End If
			End Set
		End Property
		Private _Category_ID As Global.System.Int32
		Partial Private Sub OnCategory_IDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnCategory_IDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property Category_Name() As Global.System.String
			Get
				Return _Category_Name
			End Get
			Set(ByVal value As System.String)
				OnCategory_NameChanging(value)
				ReportPropertyChanging("Category_Name")
				_Category_Name = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("Category_Name")
				OnCategory_NameChanged()
			End Set
		End Property
		Private _Category_Name As Global.System.String
		Partial Private Sub OnCategory_NameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnCategory_NameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Description() As Global.System.String
			Get
				Return _Description
			End Get
			Set(ByVal value As System.String)
				OnDescriptionChanging(value)
				ReportPropertyChanging("Description")
				_Description = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Description")
				OnDescriptionChanged()
			End Set
		End Property
		Private _Description As Global.System.String
		Partial Private Sub OnDescriptionChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnDescriptionChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Picture() As Global.System.Byte()
			Get
				Return StructuralObject.GetValidValue(_Picture)
			End Get
			Set(ByVal value As System.Byte())
				OnPictureChanging(value)
				ReportPropertyChanging("Picture")
				_Picture = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Picture")
				OnPictureChanged()
			End Set
		End Property
		Private _Picture() As Global.System.Byte
		Partial Private Sub OnPictureChanging(ByVal value() As Global.System.Byte)
		End Sub
		Partial Private Sub OnPictureChanged()
		End Sub

		#End Region


		#Region "Navigation Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<XmlIgnoreAttribute(), SoapIgnoreAttribute(), DataMemberAttribute(), EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK01", "Products")> _
		Public Property Products() As EntityCollection(Of Product)
			Get
				Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedCollection(Of Product)("NorthwindModel.Products_FK01", "Products")
			End Get
			Set(ByVal value As EntityCollection(Of Product))
				If (value IsNot Nothing) Then
					CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Product)("NorthwindModel.Products_FK01", "Products", value)
				End If
			End Set
		End Property

		#End Region

	End Class

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Product"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class Product
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new Product object.
		''' </summary>
		''' <param name="product_ID">Initial value of the Product_ID property.</param>
		''' <param name="product_Name">Initial value of the Product_Name property.</param>
		''' <param name="discontinued">Initial value of the Discontinued property.</param>
		Public Shared Function CreateProduct(ByVal product_ID As Global.System.Int32, ByVal product_Name As Global.System.String, ByVal discontinued As Global.System.Boolean) As Product
			Dim product As New Product()
			product.Product_ID = product_ID
			product.Product_Name = product_Name
			product.Discontinued = discontinued
			Return product
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property Product_ID() As Global.System.Int32
			Get
				Return _Product_ID
			End Get
			Set(ByVal value As System.Int32)
				If _Product_ID <> value Then
					OnProduct_IDChanging(value)
					ReportPropertyChanging("Product_ID")
					_Product_ID = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("Product_ID")
					OnProduct_IDChanged()
				End If
			End Set
		End Property
		Private _Product_ID As Global.System.Int32
		Partial Private Sub OnProduct_IDChanging(ByVal value As Global.System.Int32)
		End Sub
		Partial Private Sub OnProduct_IDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Supplier_ID() As Nullable(Of Global.System.Int32)
			Get
				Return _Supplier_ID
			End Get
			Set(ByVal value As Nullable(Of System.Int32))
				OnSupplier_IDChanging(value)
				ReportPropertyChanging("Supplier_ID")
				_Supplier_ID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Supplier_ID")
				OnSupplier_IDChanged()
			End Set
		End Property
		Private _Supplier_ID As Nullable(Of Global.System.Int32)
		Partial Private Sub OnSupplier_IDChanging(ByVal value As Nullable(Of Global.System.Int32))
		End Sub
		Partial Private Sub OnSupplier_IDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Category_ID() As Nullable(Of Global.System.Int32)
			Get
				Return _Category_ID
			End Get
			Set(ByVal value As Nullable(Of System.Int32))
				OnCategory_IDChanging(value)
				ReportPropertyChanging("Category_ID")
				_Category_ID = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Category_ID")
				OnCategory_IDChanged()
			End Set
		End Property
		Private _Category_ID As Nullable(Of Global.System.Int32)
		Partial Private Sub OnCategory_IDChanging(ByVal value As Nullable(Of Global.System.Int32))
		End Sub
		Partial Private Sub OnCategory_IDChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property Product_Name() As Global.System.String
			Get
				Return _Product_Name
			End Get
			Set(ByVal value As System.String)
				OnProduct_NameChanging(value)
				ReportPropertyChanging("Product_Name")
				_Product_Name = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("Product_Name")
				OnProduct_NameChanged()
			End Set
		End Property
		Private _Product_Name As Global.System.String
		Partial Private Sub OnProduct_NameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnProduct_NameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property English_Name() As Global.System.String
			Get
				Return _English_Name
			End Get
			Set(ByVal value As System.String)
				OnEnglish_NameChanging(value)
				ReportPropertyChanging("English_Name")
				_English_Name = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("English_Name")
				OnEnglish_NameChanged()
			End Set
		End Property
		Private _English_Name As Global.System.String
		Partial Private Sub OnEnglish_NameChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnEnglish_NameChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Quantity_Per_Unit() As Global.System.String
			Get
				Return _Quantity_Per_Unit
			End Get
			Set(ByVal value As System.String)
				OnQuantity_Per_UnitChanging(value)
				ReportPropertyChanging("Quantity_Per_Unit")
				_Quantity_Per_Unit = StructuralObject.SetValidValue(value, True)
				ReportPropertyChanged("Quantity_Per_Unit")
				OnQuantity_Per_UnitChanged()
			End Set
		End Property
		Private _Quantity_Per_Unit As Global.System.String
		Partial Private Sub OnQuantity_Per_UnitChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnQuantity_Per_UnitChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Unit_Price() As Nullable(Of Global.System.Decimal)
			Get
				Return _Unit_Price
			End Get
			Set(ByVal value As Nullable(Of System.Decimal))
				OnUnit_PriceChanging(value)
				ReportPropertyChanging("Unit_Price")
				_Unit_Price = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Unit_Price")
				OnUnit_PriceChanged()
			End Set
		End Property
		Private _Unit_Price As Nullable(Of Global.System.Decimal)
		Partial Private Sub OnUnit_PriceChanging(ByVal value As Nullable(Of Global.System.Decimal))
		End Sub
		Partial Private Sub OnUnit_PriceChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Units_In_Stock() As Nullable(Of Global.System.Int16)
			Get
				Return _Units_In_Stock
			End Get
			Set(ByVal value As Nullable(Of System.Int16))
				OnUnits_In_StockChanging(value)
				ReportPropertyChanging("Units_In_Stock")
				_Units_In_Stock = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Units_In_Stock")
				OnUnits_In_StockChanged()
			End Set
		End Property
		Private _Units_In_Stock As Nullable(Of Global.System.Int16)
		Partial Private Sub OnUnits_In_StockChanging(ByVal value As Nullable(Of Global.System.Int16))
		End Sub
		Partial Private Sub OnUnits_In_StockChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Units_On_Order() As Nullable(Of Global.System.Int16)
			Get
				Return _Units_On_Order
			End Get
			Set(ByVal value As Nullable(Of System.Int16))
				OnUnits_On_OrderChanging(value)
				ReportPropertyChanging("Units_On_Order")
				_Units_On_Order = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Units_On_Order")
				OnUnits_On_OrderChanged()
			End Set
		End Property
		Private _Units_On_Order As Nullable(Of Global.System.Int16)
		Partial Private Sub OnUnits_On_OrderChanging(ByVal value As Nullable(Of Global.System.Int16))
		End Sub
		Partial Private Sub OnUnits_On_OrderChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
		Public Property Reorder_Level() As Nullable(Of Global.System.Int16)
			Get
				Return _Reorder_Level
			End Get
			Set(ByVal value As Nullable(Of System.Int16))
				OnReorder_LevelChanging(value)
				ReportPropertyChanging("Reorder_Level")
				_Reorder_Level = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Reorder_Level")
				OnReorder_LevelChanged()
			End Set
		End Property
		Private _Reorder_Level As Nullable(Of Global.System.Int16)
		Partial Private Sub OnReorder_LevelChanging(ByVal value As Nullable(Of Global.System.Int16))
		End Sub
		Partial Private Sub OnReorder_LevelChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property Discontinued() As Global.System.Boolean
			Get
				Return _Discontinued
			End Get
			Set(ByVal value As System.Boolean)
				OnDiscontinuedChanging(value)
				ReportPropertyChanging("Discontinued")
				_Discontinued = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Discontinued")
				OnDiscontinuedChanged()
			End Set
		End Property
		Private _Discontinued As Global.System.Boolean
		Partial Private Sub OnDiscontinuedChanging(ByVal value As Global.System.Boolean)
		End Sub
		Partial Private Sub OnDiscontinuedChanged()
		End Sub

		#End Region


		#Region "Navigation Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<XmlIgnoreAttribute(), SoapIgnoreAttribute(), DataMemberAttribute(), EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK01", "Categories")> _
		Public Property Category() As Category
			Get
				Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Category)("NorthwindModel.Products_FK01", "Categories").Value
			End Get
			Set(ByVal value As Category)
				CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("NorthwindModel.Products_FK01", "Categories").Value = value
			End Set
		End Property
		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<BrowsableAttribute(False), DataMemberAttribute()> _
		Public Property CategoryReference() As EntityReference(Of Category)
			Get
				Return (CType(Me, IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Category)("NorthwindModel.Products_FK01", "Categories")
			End Get
			Set(ByVal value As EntityReference(Of Category))
				If (value IsNot Nothing) Then
					CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Category)("NorthwindModel.Products_FK01", "Categories", value)
				End If
			End Set
		End Property

		#End Region

	End Class

	#End Region


End Namespace
